language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
env:
- TEST_SUITE=unit
- TEST_SUITE=integration
- TEST_SUITE=regression
- TEST_SUITE=build
branches:
  only:
  - master
  - develop
  - test
jobs:
  include:
  - stage: deploy
    script: npm run build
    deploy:
    provider: npm
      email: sacha@grabyo.com
      api_key:
        secure: BK1mIl87Iqh39I96zVY8Op5alphwcdNrK2N9VwXFeBKnF+WivMDRR/BQsaT7YsnFOAfMra+vw/kz63G7MnlAzKx/u15OufzReC1ZGHOiEA5MIrg7acoO2boz1So3RUP3f+LwjPmq2roQzUaxTtwmLHsHt6JbPqV2WI/I7lvrpjsb7ZgM8jwZIlJ1vhPV3GdW3SmrhPcUxEhh60BSSLMgXvlHFTF2WJKVNQPcWIb4DcdEWcxmP2m9j4vBbi+zU1MAjUzC8/HtwGEuUTjJszMJL2YXmVmo4dZj9K66XCHzruJn7/e88BOlO9TpTSMnIX6VsZ1dW+mJHaKnSFhXf4UbDO6VkM2YtQyx0mItOMSvfBENjLAywYqGN9kYDfmNE18eJDDcpSd4HadkcIpS+wfcepAsS6La8hS++PbHjn+JIDghbiSnE7MFVZzBE8hxqXAIBzRDwtSOmPmXOAXm9zQG98+gTlidH3lJ5c8zg7OAG7aLTIyW/aSdhCN4H82GeUWXcILGh2Sz8aO+wr1/Zmd1pKShu42GP40DxyVUefG00r1H6BHFwp/CM0S0s0FiTCFdOuVO41ywEi3ndrtBObufJzZbIqnhN7Ta3asU8JErDG9VRoWCuHO53wQd1mlqVp2XagZ1amP/T3VJReymopr4TkQFEGTI5D6IdOw5fDawu1k=
      on:
        branch: test
      on:
        repo: grabyo/VideoContext
        branch: test
      skip_cleanup: true
